version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      # group non-major dev dependencies
      dev-dependencies:
        dependency-type: development
        update-types:
          - patch
          - minor

    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
      exclude:
        - github.com/einride/*
        - github.com/einride-autonomous/*
        - github.com/einride-labs/*
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 7
      exclude:
        - github.com/einride/*
        - github.com/einride-autonomous/*
        - github.com/einride-labs/*
