apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prettier-config
  title: Prettier Config
  description: Einride's default Prettier config.
  annotations:
    backstage.io/source-location: url:https://github.com/einride/prettier-config/tree/master/
    github.com/project-slug: einride/prettier-config
    github.com/team-slug: einride/asset-intelligence
spec:
  type: library
  owner: asset-intelligence
  lifecycle: production
  system: frontend-sdk
