name: Release

on:
  push:
    branches:
      - master
      - beta
      - alpha
      - next
      - next-major

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to create release
      id-token: write # to publish with provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Review
        run: yarn review

      - name: Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
